[package]
name = "margesimpson"
version = "0.0.0-dev"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
quiet_panics = "0.1.2"
rust-ini = "0.21.3"
strum = { version = "0.27.2", features = ["derive"] }
